name: GAWrapper
author: oranleiba
category: Utilities
tags: [Google Analytics, Web Analytics, Event Tracking]
docs: http://www.etootim.com/hub/ga/index.php
demo: http://www.etootim.com/hub/ga/index.php
current: 1.0.0